version: 1
groups:
  - annotation: ckanext-gztr configuration
    options:
      - key: ckanext.gztr.dataset_publisher.tiles_url
        editable: true
        description: |
          Vector tile server URL.
          Raster tiles and PMTiles are not currently supported.
          (recommended)
      - key: ckanext.gztr.dataset_publisher.default_latitude
        editable: true
        default: 34.307144
        description: |
          The default center latitude of the map.
          (recommended)
      - key: ckanext.gztr.dataset_publisher.default_longitude
        editable: true
        default: -106.018066
        descripton: |
          The default center longitude of the map.
          (recommended)
      - key: ckanext.gztr.dataset_publisher.default_zoom
        editable: true
        default: 5
        description: |
          The initial zoom level of the map.
          (recommended)
      - key: ckanext.gztr.dataset_publisher.max_bounds
        editable: true
        default: -134.428711 14.349548 -61.611328 52.536273
        description: |
          The space-separated boundaries of the map (e.g. continental USA)
          (recommended
      - key: ckanext.gztr.dataset_publisher.disable_drawn_features
        editable: true
        default: false
        description: |
          Disable drawing custom polygons for dataset publishers.
          Set this to true if you want data publishers to only use preset features provided by the sysadmin.
          (optional)
      - key: ckanext.gztr.dataset_publisher.dialog_map_height
        editable: true
        default: 60vh
        description: |
          Modify the height of the map shown in the modal (note that there is already a fullscreen button if needed).
          (optional)
      - key: ckanext.gztr.dataset_publisher.disable_address_search
        editable: true
        default: false
        description: |
          Disable the address search feature which uses the external Nominatim API.
          (optional)
      - key: ckanext.gztr.dataset_publisher.geoparquet_engine
        editable: true
        default: hyparquet
        description: |
          Select an engine for parsing GeoParquet for usage in the gazetteers.
          - hyparquet: recommended (enabled by default) for lowest bandwidth through cloud-native geospatial methodology
          - duckdb: downloads DuckDB WASM from jsdelivr.com which is slow on first request then cached on subsequent requests
          - sedonadb: not recommended, slowest implementation as it converts GeoParquet to GeoJSON and the user downloads GeoJSON
          (recommended)
      - key: ckanext.gztr.dataset_publisher.enable_stac_collection_json_button
        editable: true
        default: true
        description: |
          In a geospatial collection's info modal, display a clickable JSON file icon button to open the corresponding STAC collection page.
      - key: ckanext.gztr.dataset_publisher.enable_stac_collection_download_button
        editable: true
        default: true
        description: |
          In a geospatial collection's info modal, display a clickable download icon button to download the collection as a file (e.g. GeoParquet).
          (optional)
      - key: ckanext.gztr.public_search.tiles_url
        editable: true
        description: |
          Vector tile server URL.
          Raster tiles and PMTiles are not currently supported.
          (mandatory)
      - key: ckanext.gztr.public_search.default_latitude
        editable: true
        default: 34.407144
        description: |
          The default center latitude of the maps.
          (recommended)
      - key: ckanext.gztr.public_search.default_longitude
        editable: true
        default: -106.018066
        description: |
          The default center longitude of the maps.
          (recommended)
      - key: ckanext.gztr.public_search.default_zoom
        editable: true
        default: 5
        description: |
          The initial zoom level of the maps.
          (recommended)
      - key: ckanext.gztr.public_search.max_bounds
        editable: true
        default: -134.428711 14.349548 -61.611328 52.536273
        description: |
          The space-separated boundaries of the map (e.g. continental USA)
          (recommended)
      - key: ckanext.gztr.public_search.disable_address_search
        editable: true
        default: false
        description: |
          Disable the address search feature which uses Nominatim.
          (optional)
      - key: ckanext.gztr.public_search.enable_stac_collection_json_button
        editable: true
        default: false
        description: |
          Allow public users to click a JSON info icon button to open the STAC collection info JSON page.
          (optional)
      - key: ckanext.gztr.public_search.enable_stac_collection_download_button
        editable: true
        default: true
        description: |
          Allow public users to click a download icon button to download a geospatial collection (e.g. GeoParquet file).
          (optional)
      - key: ckanext.gztr.public_search_minimap.tiles_url
        editable: true
        description: |
          Vector, Raster, or PMTiles (using the pmtiles:// protocol) server URL.
          (mandatory)
      - key: ckanext.gztr.public_search_minimap.tiles_type
        editable: true
        default: vector
        description: |
          The type of the source, either vector or raster
          (mandatory)
      - key: ckanext.gztr.public_search_minimap.attribution_html
        editable: true
        description: |
          Attribution HTML (e.g. an HTML anchor tag with a link using href)
          NOTE: As a sysadmin, make sure this is safe HTML!
          (recommended)
      - key: ckanext.gztr.public_search_minimap.max_bounds
        editable: true
        default: -134.428711 14.349548 -61.611328 52.536273
        description: |
          The space-separated boundaries of the minimap (e.g. continental USA)
          (recommended)
      - key: ckanext.gztr.public_search_minimap.max_zoom
        editable: true
        default: 19
        description: |
          The maximum zoom level that the tiles would be retrieved for
          (optional)
      - key: ckanext.gztr.geoconnex.enabled
        editable: true
        default: false
      - key: ckanext.gztr.geoconnex.namespace
        editable: true
        description: |
          The namespace that should exist in the namespaces/bulk/ckan directory at https://github.com/internetofwater/geoconnex.us
          (optional)
      - key: ckanext.gztr.geoconnex.enable_dataset_jsonld
        editable: true
        default: false
        description: |
          Embeds Geoconnex-compatible JSON-LD within each compatible CKAN dataset's landing page
          (optional)
